services:
  chronocat-docker:
    # image: swr.cn-south-1.myhuaweicloud.com/imjcr/chronocat:latest
    tty: true
    container_name: chronocat-docker
    restart: always
    ports:
      - "5500:5500"       #satori默认端口
      - "5900:5900"       #vnc默认端口
      - "6081:6081"       #noVNC默认端口
    environment:
      - TZ=Asia/Shanghai
      - VNC_PASSWD=vncpasswd
    volumes:
      - ./config:/home/monokai/.chronocat/config
      # - ./data/QQ:/root/.config/QQ #QQ数据固化目录，请先阅读README再使用
